In [33]:
from tensorflow.keras.preprocessing.text import one_hot

In [34]:
sent=['my nane is shekhar',
     'my son name kowshik',
     'srinaish is my father',
     'lakshmamma was mother',
     'wife kalyani']

In [35]:
sent

['my nane is shekhar',
 'my son name kowshik',
 'srinaish is my father',
 'lakshmamma was mother',
 'wife kalyani']

In [36]:
voc_size=1000

In [37]:
onehot_repr=[one_hot(words,voc_size) for words in sent]
onehot_repr

[[142, 593, 641, 4],
 [142, 286, 480, 870],
 [980, 641, 142, 532],
 [305, 582, 828],
 [44, 814]]

In [38]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [39]:
import pandas as pd 
import numpy as np

In [40]:
sent_length=5

In [41]:
embedding_docs=pad_sequences(onehot_repr,padding='pre', maxlen=sent_length)

In [42]:
embedding_docs

array([[  0, 142, 593, 641,   4],
       [  0, 142, 286, 480, 870],
       [  0, 980, 641, 142, 532],
       [  0,   0, 305, 582, 828],
       [  0,   0,   0,  44, 814]])

In [43]:
dim=15

In [44]:
model=Sequential()

In [45]:
model.add(Embedding(voc_size,15,input_length=sent_length))

In [46]:
model.compile('adam','mse')

In [47]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 5, 15)             15000     
                                                                 
Total params: 15,000
Trainable params: 15,000
Non-trainable params: 0
_________________________________________________________________


In [48]:
model.predict(embedding_docs[0])

1/1 [==============================] - 0s 100ms/step


array([[ 0.02220012, -0.04057157, -0.04677555, -0.00151549,  0.04254477,
         0.0258294 , -0.00907832,  0.04453269, -0.0023882 ,  0.04927817,
        -0.02299417,  0.03364244,  0.02245232, -0.01784928,  0.03574494],
       [ 0.00889828,  0.0351685 , -0.01784547, -0.01689932,  0.01878542,
        -0.00021603,  0.00131015, -0.04559041, -0.02342006,  0.02514059,
         0.03806701, -0.02521756, -0.04217364, -0.01538166,  0.02242888],
       [ 0.00354961,  0.03398499,  0.00059044, -0.04949475,  0.01843389,
         0.00621704, -0.0002827 ,  0.02805943, -0.01662564, -0.01967745,
        -0.02764289, -0.03300156, -0.00506917, -0.00186404, -0.02178625],
       [-0.03655579,  0.03410503,  0.04576672,  0.04986704,  0.04040715,
        -0.00989204, -0.04814368, -0.00639779, -0.04627258,  0.01091242,
        -0.01287512,  0.03886736, -0.0084551 , -0.03449748, -0.02463981],
       [-0.0458869 ,  0.01619217,  0.02057404, -0.00097145, -0.01821271,
         0.03444915, -0.02102736,  0.02108829, 

In [49]:
model.predict(embedding_docs)

1/1 [==============================] - 0s 121ms/step


array([[[ 0.02220012, -0.04057157, -0.04677555, -0.00151549,
          0.04254477,  0.0258294 , -0.00907832,  0.04453269,
         -0.0023882 ,  0.04927817, -0.02299417,  0.03364244,
          0.02245232, -0.01784928,  0.03574494],
        [ 0.00889828,  0.0351685 , -0.01784547, -0.01689932,
          0.01878542, -0.00021603,  0.00131015, -0.04559041,
         -0.02342006,  0.02514059,  0.03806701, -0.02521756,
         -0.04217364, -0.01538166,  0.02242888],
        [ 0.00354961,  0.03398499,  0.00059044, -0.04949475,
          0.01843389,  0.00621704, -0.0002827 ,  0.02805943,
         -0.01662564, -0.01967745, -0.02764289, -0.03300156,
         -0.00506917, -0.00186404, -0.02178625],
        [-0.03655579,  0.03410503,  0.04576672,  0.04986704,
          0.04040715, -0.00989204, -0.04814368, -0.00639779,
         -0.04627258,  0.01091242, -0.01287512,  0.03886736,
         -0.0084551 , -0.03449748, -0.02463981],
        [-0.0458869 ,  0.01619217,  0.02057404, -0.00097145,
         -0