In [1]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 578.0 MB 15 kB/s 
     |████████████████████████████████| 438 kB 65.0 MB/s 
     |████████████████████████████████| 5.9 MB 38.4 MB/s 
     |████████████████████████████████| 1.7 MB 53.4 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.9.0
    Uninstalling tensorflow-estimator-2.9.0:
      Successfully uninstalled tensorflow-estimator-2.9.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.9.1
    Uninstalling tensorboard-2.9.1:
      Successfully uninstalled tensorboard-2.9.1
  Attempting uninstall: keras
    Found existing installation: keras 2.9.0
    Uninstalling keras-2.9.0:
      Successfully uninstalled keras-2.9.0
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 1.12
    Uninstalling flatbuffers-1.12:
      Successfully u

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[" the glass of milk",
      'the glass of juise',
      'the cup of tea',
      'i am a good boy',
      'i am a good developer',
      'underastand the meaning of words',
      'your videos are good']

In [4]:
sent

[' the glass of milk',
 'the glass of juise',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'underastand the meaning of words',
 'your videos are good']

In [12]:
voc_size=10000

In [13]:
onehot_repr=[one_hot(words,voc_size) for words in sent]

In [14]:
onehot_repr

[[993, 3683, 6295, 8043],
 [993, 3683, 6295, 4473],
 [993, 5750, 6295, 5595],
 [7383, 3196, 8266, 6288, 8840],
 [7383, 3196, 8266, 6288, 7538],
 [3469, 993, 1425, 6295, 4068],
 [7850, 2588, 8572, 6288]]

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [16]:
import numpy as np

In [18]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  993 3683 6295 8043]
 [   0    0    0    0  993 3683 6295 4473]
 [   0    0    0    0  993 5750 6295 5595]
 [   0    0    0 7383 3196 8266 6288 8840]
 [   0    0    0 7383 3196 8266 6288 7538]
 [   0    0    0 3469  993 1425 6295 4068]
 [   0    0    0    0 7850 2588 8572 6288]]


In [19]:
dim=10

In [21]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [22]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 120ms/step


array([[-0.01529083,  0.00098419,  0.03754191, -0.00142682,  0.0077273 ,
         0.03949627,  0.01937426,  0.02212906, -0.00063302, -0.01477421],
       [-0.01529083,  0.00098419,  0.03754191, -0.00142682,  0.0077273 ,
         0.03949627,  0.01937426,  0.02212906, -0.00063302, -0.01477421],
       [-0.01529083,  0.00098419,  0.03754191, -0.00142682,  0.0077273 ,
         0.03949627,  0.01937426,  0.02212906, -0.00063302, -0.01477421],
       [-0.01529083,  0.00098419,  0.03754191, -0.00142682,  0.0077273 ,
         0.03949627,  0.01937426,  0.02212906, -0.00063302, -0.01477421],
       [ 0.049081  , -0.02026292,  0.04064104, -0.03320284,  0.01870752,
         0.03665607,  0.00040274,  0.02844061,  0.01990711, -0.04514698],
       [ 0.0307156 , -0.04310882, -0.00227233,  0.00156976, -0.01188217,
         0.01038697, -0.04748994,  0.02404219, -0.0382333 , -0.00171085],
       [-0.01837982, -0.03122826,  0.03286156,  0.00777595,  0.01259252,
        -0.03374817, -0.00393452, -0.0413987 

In [24]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 44ms/step


array([[[-0.01529083,  0.00098419,  0.03754191, -0.00142682,
          0.0077273 ,  0.03949627,  0.01937426,  0.02212906,
         -0.00063302, -0.01477421],
        [-0.01529083,  0.00098419,  0.03754191, -0.00142682,
          0.0077273 ,  0.03949627,  0.01937426,  0.02212906,
         -0.00063302, -0.01477421],
        [-0.01529083,  0.00098419,  0.03754191, -0.00142682,
          0.0077273 ,  0.03949627,  0.01937426,  0.02212906,
         -0.00063302, -0.01477421],
        [-0.01529083,  0.00098419,  0.03754191, -0.00142682,
          0.0077273 ,  0.03949627,  0.01937426,  0.02212906,
         -0.00063302, -0.01477421],
        [ 0.049081  , -0.02026292,  0.04064104, -0.03320284,
          0.01870752,  0.03665607,  0.00040274,  0.02844061,
          0.01990711, -0.04514698],
        [ 0.0307156 , -0.04310882, -0.00227233,  0.00156976,
         -0.01188217,  0.01038697, -0.04748994,  0.02404219,
         -0.0382333 , -0.00171085],
        [-0.01837982, -0.03122826,  0.03286156,  0.0